version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "127.0.0.1:8105:6379"
    networks:
      - web

  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - "8104:8080"
    environment:
      AUTHENTICATION_API_KEY: "bXVkZS1tZQ=="
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      DATABASE_CONNECTION_URI: "postgresql://postgres:postgres@postgres_container:5432/evolution"
      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: "redis://redis_container:6379"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - web
      - postgres_network

volumes:
  evolution_instances:

networks:
  web:
    external: true
  postgres_network:
    external: true