version: '3.8'

services:
  gerenciador_usuarios:
    container_name: "Gerenciador_De_Usuarios_PHP"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - web
    restart: unless-stopped

  nginx:
    container_name: Gerenciador_De_Usuarios_nginx
    image: nginx:latest
    ports:
      - "8184:80"
      # - "447:443"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
    depends_on:
      - gerenciador_usuarios
    restart: unless-stopped

networks:
  web:
    external: true
