version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "BB_API_1a_SENTENCA"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "8086:8000"
    networks:
      - nit
networks:
  nit:
    external: true
