version: '3'
services:
    python-app:
        build: ./python-app
        environment:
            MCP_SERVER_URL: http://playwright-mcp:8106
        depends_on:
            - playwright-mcp

    playwright-mcp:
        image: node:latest
        command: npx @playwright/mcp@latest --port 8106
        ports:
            - "8106:8106"
